//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormGUI.WinFormSample.ReverseReference.RR10_EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRR_tb
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
